/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedLayoutRouteImport } from './routes/_authenticated/_layout'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authCompanyOnboardingRouteImport } from './routes/(auth)/company-onboarding'
import { Route as AuthenticatedLayoutCustomerIndexRouteImport } from './routes/_authenticated/_layout/customer/index'
import { Route as AuthenticatedLayoutMarketerOverviewRouteImport } from './routes/_authenticated/_layout/marketer/overview'
import { Route as AuthenticatedLayoutCompanyLayoutRouteImport } from './routes/_authenticated/_layout/company/_layout'
import { Route as AuthenticatedLayoutCompanyLayoutPayoutsRouteImport } from './routes/_authenticated/_layout/company/_layout/payouts'
import { Route as AuthenticatedLayoutCompanyLayoutOverviewRouteImport } from './routes/_authenticated/_layout/company/_layout/overview'
import { Route as AuthenticatedLayoutCompanyLayoutApplicationsRouteImport } from './routes/_authenticated/_layout/company/_layout/applications'
import { Route as AuthenticatedLayoutCompanyLayoutAnalyticsRouteImport } from './routes/_authenticated/_layout/company/_layout/analytics'
import { Route as AuthenticatedLayoutCompanyLayoutProductsIndexRouteImport } from './routes/_authenticated/_layout/company/_layout/products/index'
import { Route as AuthenticatedLayoutCompanyLayoutMarketersIndexRouteImport } from './routes/_authenticated/_layout/company/_layout/marketers/index'
import { Route as AuthenticatedLayoutCompanyLayoutApprovalsIndexRouteImport } from './routes/_authenticated/_layout/company/_layout/approvals/index'
import { Route as AuthenticatedLayoutCompanyLayoutAdminsIndexRouteImport } from './routes/_authenticated/_layout/company/_layout/admins/index'
import { Route as AuthenticatedLayoutCompanyLayoutProductsNewRouteImport } from './routes/_authenticated/_layout/company/_layout/products/new'
import { Route as AuthenticatedLayoutCompanyLayoutProductsProductIdProductNameIndexRouteImport } from './routes/_authenticated/_layout/company/_layout/products/$productId/$product-name/index'
import { Route as AuthenticatedLayoutCompanyLayoutMarketersMarketerIdMarketerNameIndexRouteImport } from './routes/_authenticated/_layout/company/_layout/marketers/$marketerId/$marketer-name/index'
import { Route as AuthenticatedLayoutCompanyLayoutAdminsAdminIdAdminNameIndexRouteImport } from './routes/_authenticated/_layout/company/_layout/admins/$adminId/$admin-name/index'

const AuthenticatedLayoutCompanyRouteImport = createFileRoute(
  '/_authenticated/_layout/company',
)()

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLayoutRoute = AuthenticatedLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authCompanyOnboardingRoute = authCompanyOnboardingRouteImport.update({
  id: '/(auth)/company-onboarding',
  path: '/company-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLayoutCompanyRoute =
  AuthenticatedLayoutCompanyRouteImport.update({
    id: '/company',
    path: '/company',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutCustomerIndexRoute =
  AuthenticatedLayoutCustomerIndexRouteImport.update({
    id: '/customer/',
    path: '/customer/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutMarketerOverviewRoute =
  AuthenticatedLayoutMarketerOverviewRouteImport.update({
    id: '/marketer/overview',
    path: '/marketer/overview',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutCompanyLayoutRoute =
  AuthenticatedLayoutCompanyLayoutRouteImport.update({
    id: '/_layout',
    getParentRoute: () => AuthenticatedLayoutCompanyRoute,
  } as any)
const AuthenticatedLayoutCompanyLayoutPayoutsRoute =
  AuthenticatedLayoutCompanyLayoutPayoutsRouteImport.update({
    id: '/payouts',
    path: '/payouts',
    getParentRoute: () => AuthenticatedLayoutCompanyLayoutRoute,
  } as any)
const AuthenticatedLayoutCompanyLayoutOverviewRoute =
  AuthenticatedLayoutCompanyLayoutOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AuthenticatedLayoutCompanyLayoutRoute,
  } as any)
const AuthenticatedLayoutCompanyLayoutApplicationsRoute =
  AuthenticatedLayoutCompanyLayoutApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedLayoutCompanyLayoutRoute,
  } as any)
const AuthenticatedLayoutCompanyLayoutAnalyticsRoute =
  AuthenticatedLayoutCompanyLayoutAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedLayoutCompanyLayoutRoute,
  } as any)
const AuthenticatedLayoutCompanyLayoutProductsIndexRoute =
  AuthenticatedLayoutCompanyLayoutProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedLayoutCompanyLayoutRoute,
  } as any)
const AuthenticatedLayoutCompanyLayoutMarketersIndexRoute =
  AuthenticatedLayoutCompanyLayoutMarketersIndexRouteImport.update({
    id: '/marketers/',
    path: '/marketers/',
    getParentRoute: () => AuthenticatedLayoutCompanyLayoutRoute,
  } as any)
const AuthenticatedLayoutCompanyLayoutApprovalsIndexRoute =
  AuthenticatedLayoutCompanyLayoutApprovalsIndexRouteImport.update({
    id: '/approvals/',
    path: '/approvals/',
    getParentRoute: () => AuthenticatedLayoutCompanyLayoutRoute,
  } as any)
const AuthenticatedLayoutCompanyLayoutAdminsIndexRoute =
  AuthenticatedLayoutCompanyLayoutAdminsIndexRouteImport.update({
    id: '/admins/',
    path: '/admins/',
    getParentRoute: () => AuthenticatedLayoutCompanyLayoutRoute,
  } as any)
const AuthenticatedLayoutCompanyLayoutProductsNewRoute =
  AuthenticatedLayoutCompanyLayoutProductsNewRouteImport.update({
    id: '/products/new',
    path: '/products/new',
    getParentRoute: () => AuthenticatedLayoutCompanyLayoutRoute,
  } as any)
const AuthenticatedLayoutCompanyLayoutProductsProductIdProductNameIndexRoute =
  AuthenticatedLayoutCompanyLayoutProductsProductIdProductNameIndexRouteImport.update(
    {
      id: '/products/$productId/$product-name/',
      path: '/products/$productId/$product-name/',
      getParentRoute: () => AuthenticatedLayoutCompanyLayoutRoute,
    } as any,
  )
const AuthenticatedLayoutCompanyLayoutMarketersMarketerIdMarketerNameIndexRoute =
  AuthenticatedLayoutCompanyLayoutMarketersMarketerIdMarketerNameIndexRouteImport.update(
    {
      id: '/marketers/$marketerId/$marketer-name/',
      path: '/marketers/$marketerId/$marketer-name/',
      getParentRoute: () => AuthenticatedLayoutCompanyLayoutRoute,
    } as any,
  )
const AuthenticatedLayoutCompanyLayoutAdminsAdminIdAdminNameIndexRoute =
  AuthenticatedLayoutCompanyLayoutAdminsAdminIdAdminNameIndexRouteImport.update(
    {
      id: '/admins/$adminId/$admin-name/',
      path: '/admins/$adminId/$admin-name/',
      getParentRoute: () => AuthenticatedLayoutCompanyLayoutRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/company-onboarding': typeof authCompanyOnboardingRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/company': typeof AuthenticatedLayoutCompanyLayoutRouteWithChildren
  '/marketer/overview': typeof AuthenticatedLayoutMarketerOverviewRoute
  '/customer': typeof AuthenticatedLayoutCustomerIndexRoute
  '/company/analytics': typeof AuthenticatedLayoutCompanyLayoutAnalyticsRoute
  '/company/applications': typeof AuthenticatedLayoutCompanyLayoutApplicationsRoute
  '/company/overview': typeof AuthenticatedLayoutCompanyLayoutOverviewRoute
  '/company/payouts': typeof AuthenticatedLayoutCompanyLayoutPayoutsRoute
  '/company/products/new': typeof AuthenticatedLayoutCompanyLayoutProductsNewRoute
  '/company/admins': typeof AuthenticatedLayoutCompanyLayoutAdminsIndexRoute
  '/company/approvals': typeof AuthenticatedLayoutCompanyLayoutApprovalsIndexRoute
  '/company/marketers': typeof AuthenticatedLayoutCompanyLayoutMarketersIndexRoute
  '/company/products': typeof AuthenticatedLayoutCompanyLayoutProductsIndexRoute
  '/company/admins/$adminId/$admin-name': typeof AuthenticatedLayoutCompanyLayoutAdminsAdminIdAdminNameIndexRoute
  '/company/marketers/$marketerId/$marketer-name': typeof AuthenticatedLayoutCompanyLayoutMarketersMarketerIdMarketerNameIndexRoute
  '/company/products/$productId/$product-name': typeof AuthenticatedLayoutCompanyLayoutProductsProductIdProductNameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/company-onboarding': typeof authCompanyOnboardingRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/company': typeof AuthenticatedLayoutCompanyLayoutRouteWithChildren
  '/marketer/overview': typeof AuthenticatedLayoutMarketerOverviewRoute
  '/customer': typeof AuthenticatedLayoutCustomerIndexRoute
  '/company/analytics': typeof AuthenticatedLayoutCompanyLayoutAnalyticsRoute
  '/company/applications': typeof AuthenticatedLayoutCompanyLayoutApplicationsRoute
  '/company/overview': typeof AuthenticatedLayoutCompanyLayoutOverviewRoute
  '/company/payouts': typeof AuthenticatedLayoutCompanyLayoutPayoutsRoute
  '/company/products/new': typeof AuthenticatedLayoutCompanyLayoutProductsNewRoute
  '/company/admins': typeof AuthenticatedLayoutCompanyLayoutAdminsIndexRoute
  '/company/approvals': typeof AuthenticatedLayoutCompanyLayoutApprovalsIndexRoute
  '/company/marketers': typeof AuthenticatedLayoutCompanyLayoutMarketersIndexRoute
  '/company/products': typeof AuthenticatedLayoutCompanyLayoutProductsIndexRoute
  '/company/admins/$adminId/$admin-name': typeof AuthenticatedLayoutCompanyLayoutAdminsAdminIdAdminNameIndexRoute
  '/company/marketers/$marketerId/$marketer-name': typeof AuthenticatedLayoutCompanyLayoutMarketersMarketerIdMarketerNameIndexRoute
  '/company/products/$productId/$product-name': typeof AuthenticatedLayoutCompanyLayoutProductsProductIdProductNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/(auth)/company-onboarding': typeof authCompanyOnboardingRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/_authenticated/_layout': typeof AuthenticatedLayoutRouteWithChildren
  '/_authenticated/_layout/company': typeof AuthenticatedLayoutCompanyRouteWithChildren
  '/_authenticated/_layout/company/_layout': typeof AuthenticatedLayoutCompanyLayoutRouteWithChildren
  '/_authenticated/_layout/marketer/overview': typeof AuthenticatedLayoutMarketerOverviewRoute
  '/_authenticated/_layout/customer/': typeof AuthenticatedLayoutCustomerIndexRoute
  '/_authenticated/_layout/company/_layout/analytics': typeof AuthenticatedLayoutCompanyLayoutAnalyticsRoute
  '/_authenticated/_layout/company/_layout/applications': typeof AuthenticatedLayoutCompanyLayoutApplicationsRoute
  '/_authenticated/_layout/company/_layout/overview': typeof AuthenticatedLayoutCompanyLayoutOverviewRoute
  '/_authenticated/_layout/company/_layout/payouts': typeof AuthenticatedLayoutCompanyLayoutPayoutsRoute
  '/_authenticated/_layout/company/_layout/products/new': typeof AuthenticatedLayoutCompanyLayoutProductsNewRoute
  '/_authenticated/_layout/company/_layout/admins/': typeof AuthenticatedLayoutCompanyLayoutAdminsIndexRoute
  '/_authenticated/_layout/company/_layout/approvals/': typeof AuthenticatedLayoutCompanyLayoutApprovalsIndexRoute
  '/_authenticated/_layout/company/_layout/marketers/': typeof AuthenticatedLayoutCompanyLayoutMarketersIndexRoute
  '/_authenticated/_layout/company/_layout/products/': typeof AuthenticatedLayoutCompanyLayoutProductsIndexRoute
  '/_authenticated/_layout/company/_layout/admins/$adminId/$admin-name/': typeof AuthenticatedLayoutCompanyLayoutAdminsAdminIdAdminNameIndexRoute
  '/_authenticated/_layout/company/_layout/marketers/$marketerId/$marketer-name/': typeof AuthenticatedLayoutCompanyLayoutMarketersMarketerIdMarketerNameIndexRoute
  '/_authenticated/_layout/company/_layout/products/$productId/$product-name/': typeof AuthenticatedLayoutCompanyLayoutProductsProductIdProductNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/company-onboarding'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/company'
    | '/marketer/overview'
    | '/customer'
    | '/company/analytics'
    | '/company/applications'
    | '/company/overview'
    | '/company/payouts'
    | '/company/products/new'
    | '/company/admins'
    | '/company/approvals'
    | '/company/marketers'
    | '/company/products'
    | '/company/admins/$adminId/$admin-name'
    | '/company/marketers/$marketerId/$marketer-name'
    | '/company/products/$productId/$product-name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/company-onboarding'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/company'
    | '/marketer/overview'
    | '/customer'
    | '/company/analytics'
    | '/company/applications'
    | '/company/overview'
    | '/company/payouts'
    | '/company/products/new'
    | '/company/admins'
    | '/company/approvals'
    | '/company/marketers'
    | '/company/products'
    | '/company/admins/$adminId/$admin-name'
    | '/company/marketers/$marketerId/$marketer-name'
    | '/company/products/$productId/$product-name'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/(auth)/company-onboarding'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/reset-password'
    | '/_authenticated/_layout'
    | '/_authenticated/_layout/company'
    | '/_authenticated/_layout/company/_layout'
    | '/_authenticated/_layout/marketer/overview'
    | '/_authenticated/_layout/customer/'
    | '/_authenticated/_layout/company/_layout/analytics'
    | '/_authenticated/_layout/company/_layout/applications'
    | '/_authenticated/_layout/company/_layout/overview'
    | '/_authenticated/_layout/company/_layout/payouts'
    | '/_authenticated/_layout/company/_layout/products/new'
    | '/_authenticated/_layout/company/_layout/admins/'
    | '/_authenticated/_layout/company/_layout/approvals/'
    | '/_authenticated/_layout/company/_layout/marketers/'
    | '/_authenticated/_layout/company/_layout/products/'
    | '/_authenticated/_layout/company/_layout/admins/$adminId/$admin-name/'
    | '/_authenticated/_layout/company/_layout/marketers/$marketerId/$marketer-name/'
    | '/_authenticated/_layout/company/_layout/products/$productId/$product-name/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  authCompanyOnboardingRoute: typeof authCompanyOnboardingRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_layout': {
      id: '/_authenticated/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedLayoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/company-onboarding': {
      id: '/(auth)/company-onboarding'
      path: '/company-onboarding'
      fullPath: '/company-onboarding'
      preLoaderRoute: typeof authCompanyOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_layout/company': {
      id: '/_authenticated/_layout/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof AuthenticatedLayoutCompanyRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/customer/': {
      id: '/_authenticated/_layout/customer/'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof AuthenticatedLayoutCustomerIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/marketer/overview': {
      id: '/_authenticated/_layout/marketer/overview'
      path: '/marketer/overview'
      fullPath: '/marketer/overview'
      preLoaderRoute: typeof AuthenticatedLayoutMarketerOverviewRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/company/_layout': {
      id: '/_authenticated/_layout/company/_layout'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof AuthenticatedLayoutCompanyLayoutRouteImport
      parentRoute: typeof AuthenticatedLayoutCompanyRoute
    }
    '/_authenticated/_layout/company/_layout/payouts': {
      id: '/_authenticated/_layout/company/_layout/payouts'
      path: '/payouts'
      fullPath: '/company/payouts'
      preLoaderRoute: typeof AuthenticatedLayoutCompanyLayoutPayoutsRouteImport
      parentRoute: typeof AuthenticatedLayoutCompanyLayoutRoute
    }
    '/_authenticated/_layout/company/_layout/overview': {
      id: '/_authenticated/_layout/company/_layout/overview'
      path: '/overview'
      fullPath: '/company/overview'
      preLoaderRoute: typeof AuthenticatedLayoutCompanyLayoutOverviewRouteImport
      parentRoute: typeof AuthenticatedLayoutCompanyLayoutRoute
    }
    '/_authenticated/_layout/company/_layout/applications': {
      id: '/_authenticated/_layout/company/_layout/applications'
      path: '/applications'
      fullPath: '/company/applications'
      preLoaderRoute: typeof AuthenticatedLayoutCompanyLayoutApplicationsRouteImport
      parentRoute: typeof AuthenticatedLayoutCompanyLayoutRoute
    }
    '/_authenticated/_layout/company/_layout/analytics': {
      id: '/_authenticated/_layout/company/_layout/analytics'
      path: '/analytics'
      fullPath: '/company/analytics'
      preLoaderRoute: typeof AuthenticatedLayoutCompanyLayoutAnalyticsRouteImport
      parentRoute: typeof AuthenticatedLayoutCompanyLayoutRoute
    }
    '/_authenticated/_layout/company/_layout/products/': {
      id: '/_authenticated/_layout/company/_layout/products/'
      path: '/products'
      fullPath: '/company/products'
      preLoaderRoute: typeof AuthenticatedLayoutCompanyLayoutProductsIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutCompanyLayoutRoute
    }
    '/_authenticated/_layout/company/_layout/marketers/': {
      id: '/_authenticated/_layout/company/_layout/marketers/'
      path: '/marketers'
      fullPath: '/company/marketers'
      preLoaderRoute: typeof AuthenticatedLayoutCompanyLayoutMarketersIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutCompanyLayoutRoute
    }
    '/_authenticated/_layout/company/_layout/approvals/': {
      id: '/_authenticated/_layout/company/_layout/approvals/'
      path: '/approvals'
      fullPath: '/company/approvals'
      preLoaderRoute: typeof AuthenticatedLayoutCompanyLayoutApprovalsIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutCompanyLayoutRoute
    }
    '/_authenticated/_layout/company/_layout/admins/': {
      id: '/_authenticated/_layout/company/_layout/admins/'
      path: '/admins'
      fullPath: '/company/admins'
      preLoaderRoute: typeof AuthenticatedLayoutCompanyLayoutAdminsIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutCompanyLayoutRoute
    }
    '/_authenticated/_layout/company/_layout/products/new': {
      id: '/_authenticated/_layout/company/_layout/products/new'
      path: '/products/new'
      fullPath: '/company/products/new'
      preLoaderRoute: typeof AuthenticatedLayoutCompanyLayoutProductsNewRouteImport
      parentRoute: typeof AuthenticatedLayoutCompanyLayoutRoute
    }
    '/_authenticated/_layout/company/_layout/products/$productId/$product-name/': {
      id: '/_authenticated/_layout/company/_layout/products/$productId/$product-name/'
      path: '/products/$productId/$product-name'
      fullPath: '/company/products/$productId/$product-name'
      preLoaderRoute: typeof AuthenticatedLayoutCompanyLayoutProductsProductIdProductNameIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutCompanyLayoutRoute
    }
    '/_authenticated/_layout/company/_layout/marketers/$marketerId/$marketer-name/': {
      id: '/_authenticated/_layout/company/_layout/marketers/$marketerId/$marketer-name/'
      path: '/marketers/$marketerId/$marketer-name'
      fullPath: '/company/marketers/$marketerId/$marketer-name'
      preLoaderRoute: typeof AuthenticatedLayoutCompanyLayoutMarketersMarketerIdMarketerNameIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutCompanyLayoutRoute
    }
    '/_authenticated/_layout/company/_layout/admins/$adminId/$admin-name/': {
      id: '/_authenticated/_layout/company/_layout/admins/$adminId/$admin-name/'
      path: '/admins/$adminId/$admin-name'
      fullPath: '/company/admins/$adminId/$admin-name'
      preLoaderRoute: typeof AuthenticatedLayoutCompanyLayoutAdminsAdminIdAdminNameIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutCompanyLayoutRoute
    }
  }
}

interface AuthenticatedLayoutCompanyLayoutRouteChildren {
  AuthenticatedLayoutCompanyLayoutAnalyticsRoute: typeof AuthenticatedLayoutCompanyLayoutAnalyticsRoute
  AuthenticatedLayoutCompanyLayoutApplicationsRoute: typeof AuthenticatedLayoutCompanyLayoutApplicationsRoute
  AuthenticatedLayoutCompanyLayoutOverviewRoute: typeof AuthenticatedLayoutCompanyLayoutOverviewRoute
  AuthenticatedLayoutCompanyLayoutPayoutsRoute: typeof AuthenticatedLayoutCompanyLayoutPayoutsRoute
  AuthenticatedLayoutCompanyLayoutProductsNewRoute: typeof AuthenticatedLayoutCompanyLayoutProductsNewRoute
  AuthenticatedLayoutCompanyLayoutAdminsIndexRoute: typeof AuthenticatedLayoutCompanyLayoutAdminsIndexRoute
  AuthenticatedLayoutCompanyLayoutApprovalsIndexRoute: typeof AuthenticatedLayoutCompanyLayoutApprovalsIndexRoute
  AuthenticatedLayoutCompanyLayoutMarketersIndexRoute: typeof AuthenticatedLayoutCompanyLayoutMarketersIndexRoute
  AuthenticatedLayoutCompanyLayoutProductsIndexRoute: typeof AuthenticatedLayoutCompanyLayoutProductsIndexRoute
  AuthenticatedLayoutCompanyLayoutAdminsAdminIdAdminNameIndexRoute: typeof AuthenticatedLayoutCompanyLayoutAdminsAdminIdAdminNameIndexRoute
  AuthenticatedLayoutCompanyLayoutMarketersMarketerIdMarketerNameIndexRoute: typeof AuthenticatedLayoutCompanyLayoutMarketersMarketerIdMarketerNameIndexRoute
  AuthenticatedLayoutCompanyLayoutProductsProductIdProductNameIndexRoute: typeof AuthenticatedLayoutCompanyLayoutProductsProductIdProductNameIndexRoute
}

const AuthenticatedLayoutCompanyLayoutRouteChildren: AuthenticatedLayoutCompanyLayoutRouteChildren =
  {
    AuthenticatedLayoutCompanyLayoutAnalyticsRoute:
      AuthenticatedLayoutCompanyLayoutAnalyticsRoute,
    AuthenticatedLayoutCompanyLayoutApplicationsRoute:
      AuthenticatedLayoutCompanyLayoutApplicationsRoute,
    AuthenticatedLayoutCompanyLayoutOverviewRoute:
      AuthenticatedLayoutCompanyLayoutOverviewRoute,
    AuthenticatedLayoutCompanyLayoutPayoutsRoute:
      AuthenticatedLayoutCompanyLayoutPayoutsRoute,
    AuthenticatedLayoutCompanyLayoutProductsNewRoute:
      AuthenticatedLayoutCompanyLayoutProductsNewRoute,
    AuthenticatedLayoutCompanyLayoutAdminsIndexRoute:
      AuthenticatedLayoutCompanyLayoutAdminsIndexRoute,
    AuthenticatedLayoutCompanyLayoutApprovalsIndexRoute:
      AuthenticatedLayoutCompanyLayoutApprovalsIndexRoute,
    AuthenticatedLayoutCompanyLayoutMarketersIndexRoute:
      AuthenticatedLayoutCompanyLayoutMarketersIndexRoute,
    AuthenticatedLayoutCompanyLayoutProductsIndexRoute:
      AuthenticatedLayoutCompanyLayoutProductsIndexRoute,
    AuthenticatedLayoutCompanyLayoutAdminsAdminIdAdminNameIndexRoute:
      AuthenticatedLayoutCompanyLayoutAdminsAdminIdAdminNameIndexRoute,
    AuthenticatedLayoutCompanyLayoutMarketersMarketerIdMarketerNameIndexRoute:
      AuthenticatedLayoutCompanyLayoutMarketersMarketerIdMarketerNameIndexRoute,
    AuthenticatedLayoutCompanyLayoutProductsProductIdProductNameIndexRoute:
      AuthenticatedLayoutCompanyLayoutProductsProductIdProductNameIndexRoute,
  }

const AuthenticatedLayoutCompanyLayoutRouteWithChildren =
  AuthenticatedLayoutCompanyLayoutRoute._addFileChildren(
    AuthenticatedLayoutCompanyLayoutRouteChildren,
  )

interface AuthenticatedLayoutCompanyRouteChildren {
  AuthenticatedLayoutCompanyLayoutRoute: typeof AuthenticatedLayoutCompanyLayoutRouteWithChildren
}

const AuthenticatedLayoutCompanyRouteChildren: AuthenticatedLayoutCompanyRouteChildren =
  {
    AuthenticatedLayoutCompanyLayoutRoute:
      AuthenticatedLayoutCompanyLayoutRouteWithChildren,
  }

const AuthenticatedLayoutCompanyRouteWithChildren =
  AuthenticatedLayoutCompanyRoute._addFileChildren(
    AuthenticatedLayoutCompanyRouteChildren,
  )

interface AuthenticatedLayoutRouteChildren {
  AuthenticatedLayoutCompanyRoute: typeof AuthenticatedLayoutCompanyRouteWithChildren
  AuthenticatedLayoutMarketerOverviewRoute: typeof AuthenticatedLayoutMarketerOverviewRoute
  AuthenticatedLayoutCustomerIndexRoute: typeof AuthenticatedLayoutCustomerIndexRoute
}

const AuthenticatedLayoutRouteChildren: AuthenticatedLayoutRouteChildren = {
  AuthenticatedLayoutCompanyRoute: AuthenticatedLayoutCompanyRouteWithChildren,
  AuthenticatedLayoutMarketerOverviewRoute:
    AuthenticatedLayoutMarketerOverviewRoute,
  AuthenticatedLayoutCustomerIndexRoute: AuthenticatedLayoutCustomerIndexRoute,
}

const AuthenticatedLayoutRouteWithChildren =
  AuthenticatedLayoutRoute._addFileChildren(AuthenticatedLayoutRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedLayoutRoute: typeof AuthenticatedLayoutRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedLayoutRoute: AuthenticatedLayoutRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  authCompanyOnboardingRoute: authCompanyOnboardingRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authResetPasswordRoute: authResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
